### ISSUE TITLE
'vis_tool' object has no attribute 'data_info

### ISSUE THREAD

**Issue by EudicL** [Chien-Hung/DetVisGUI#15]
Hello. when i run the code, the issue was below:
Traceback (most recent call last):
  File "DetVisGUI/DetVisGUI.py", line 1348, in <module>
    vis_tool().run()
  File "DetVisGUI/DetVisGUI.py", line 366, in __init__
    self.info.set('DATASET: {}'.format(self.data_info.dataset))
AttributeError: 'vis_tool' object has no attribute 'data_info'

**Comment by SunxzY** [comment]
I get the same error

**Comment by SunxzY** [comment]
![image](https://github.com/Chien-Hung/DetVisGUI/assets/91373768/e75ea392-b673-4965-a307-61dac49bf729)
The annotation format of my customized dataset is the format of the COCO dataset. The following image is my solution
