### ISSUE TITLE
Unable to run inference in GUI

### ISSUE THREAD

**Issue by achaiah** [Chien-Hung/DetVisGUI#8]
Hi,

Thanks for the tool. Unfortunately I don't seem to be able to make it work when trying your example:

`python DetVisGUI_test.py configs/faster_rcnn_r50_fpn_1x_coco.py ./faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth data/test_images
`
Results in:

```
Traceback (most recent call last):
  File "DetVisGUI_test.py", line 910, in <module>
    vis_tool().run()
  File "DetVisGUI_test.py", line 884, in run
    self.clear_add_listBox_img()
  File "DetVisGUI_test.py", line 754, in clear_add_listBox_img
    self.change_img()
  File "DetVisGUI_test.py", line 450, in change_img
    result = inference_detector(self.model, img)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/apis/inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 173, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 177, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/dense_test_mixins.py", line 124, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 128, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 220, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/Users/a_s/anaconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 47, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'nms'
```

Any ideas on what might be wrong?

Thanks

**Comment by PolarBear-J** [comment]
I have the same problem. Have you solved it?
